# Generated by Django 3.0.7 on 2020-06-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='popularity_rate',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='satisfaction_rate',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
