# Generated by Django 3.0.7 on 2020-06-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0006_auto_20200628_1508"),
    ]

    operations = [
        migrations.RemoveField(model_name="segment", name="size",),
    ]
