#+HTML_HEAD: <link href="https://github.com/kaushalmodi/.emacs.d/blob/master/misc/css/leuven_theme.css" rel="stylesheet">
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-bigblow.setup
#+OPTIONS: ^:nil
#+TITLE: Python Developer - Mikel Losada

* DOCS
** Get Docker
https://docs.docker.com/engine/install/

** Running Docker as a non sudo user
https://docs.docker.com/engine/install/linux-postinstall/

** Make commands
*** setupmysql
Creates the python_developer SQL database.

Creates the mikel user with password 'mikel' and grants it all privileges, flushing them afterwards.

*You will need to run this command after you do a fresh build.*
*** up
Runs Django, MariaDB and MongoDB containers.

Access Django at 
#+BEGIN_SRC 
0.0.0.0:8000 
#+END_SRC
*** build
Builds Django, MariaDB and MongoDB containers.
*** createsuperuser
Creates a Django superuser.

Run this once to create a superuser and access the admin site at 
#+BEGIN_SRC 
0.0.0.0:8000/admin
#+END_SRC 
*** loadmongo
Creates a Mongo collection in the python_developer_db database.

*segments_input.json* and *restaurants_input.json* must be in the root folder.
*** loadsql
Populates the python_developer MySQL database.

*segments_input.json* and *restaurants_input.json* must be in the root folder.
*** dumpmongo
Creates a dump of the python_developer_db Mongo database using mongodump. 

This dump is gzip-compressed.
*** dumpsql
Creates a dump of the python_developer MySQL database using mysqldump. 

This dump is in SQL format.
*** dumpsqltojson
Creates a dump of the python_developer MySQL database using the dumpsqltojson custom django-admin command.

This dump is in JSON format.

** MongoDB

** MariaDB

** FAQ
*** What tool did you use to create this documentation?
Emacs and org-mode, with the [[https://fniessen.github.io/org-html-themes/setup/theme-bigblow.setup][Big Blow theme]]. The source is docs.org (in this folder).

*** How do you generate HTML on Org Mode?
[[https://orgmode.org/manual/HTML-export-commands.html#HTML-export-commands][By pressing C-c C-e h-h]].

*** How did you set up this project?
[[https://github.com/pydanny/cookiecutter-django][I used Django Cookiecutter]].
