version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  mysql:
    image: mariadb
    container_name: python_developer_mysql
    restart: always
    env_file: 
      - ./.envs/.local/.mariadb
    ports:
      - 3306:3306
    expose:
      - 3306
  mongo:
    image: mongo
    container_name: python_developer_mongo
    command: ["--bind_ip_all"]
    restart: always
    ports:
      - 27017:27017
    env_file: 
      - ./.envs/.local/.mongodb
    volumes:
      - .:/mongodata
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: python_developer_local_django
    container_name: django
    depends_on:
      - mysql
      - mongo
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.mariadb
      - ./.envs/.local/.mongodb          
    ports:
      - "8000:8000"
    command: /start        

